=== tanaselaura/Java6TanaseLaura/Java6TanaseLaura/src/xml/Users.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--Define Users vocabulary/syntax.   
Table with many users records.
One user has one cnp, name, password-->
<!ELEMENT users (user)*>
<!ELEMENT user (cnp, name, password)>
<!ELEMENT cnp (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== tanaselaura/Java6TanaseLaura/Java6TanaseLaura/src/xml/Users.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE users SYSTEM "Users.dtd">
<!-- users XML file with their cnp, names and passwords
-->

<users>
    <user>
        <cnp>2951101151934</cnp>
        <name>laura</name>
        <password>laura</password>
    </user>
    <user>
        <cnp>2942006151934</cnp>
        <name>maria</name>
        <password>maria</password>
    </user>
    <user>
        <cnp>1950202948259</cnp>
        <name>laurentiu</name>
        <password>laurentiu</password>
    </user>        
</users>
